apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cluster-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /storage
        backend:
          serviceName: vinnsl-storage-service
          servicePort: 8081
      - path: /vinnsl
        backend:
          serviceName: vinnsl-service
          servicePort: 8080